### PR TITLE
Fix/docu api structure - reduce TOC depth level

### PR DESCRIPTION
**Pull request by jakob-wo**
This PR changes the structure of the API section in the documentation.

1) I wanted to reduce the depth-level of the TOC because in oemof-thermal we just have modules but no other packages. All modules shall be visible at the first level of the API overview.

2) I wanted to provide a structure we can use for the coming PRs of the components.

### CODE REVIEW

**Review by jnnr — APPROVED** [review]
Looks better! Thanks for fixing that.

**Comment by jakob-wo** [comment]
Does anyone know what causes the checks to fail?

**Comment by jnnr** [comment]
It fails because there are no tests yet in the test directory. We can ignore that for the moment.

**Comment by uvchik** [comment]
You could also add a dummy test, because if test fail all the time won't notice if something else is wrong.

```python
def my_dummy_test()
    assert 5 == 5
```

**Comment by FranziPl** [comment]
Looks good to me

**Review by FranziPl — COMMENTED** [review]
Looks good to me.

**Review by FranziPl — APPROVED** [review]

**Comment by jnnr** [comment]
> You could also add a dummy test, because if test fail all the time won't notice if something else is wrong.
> 
> ```python
> def my_dummy_test()
>     assert 5 == 5
> ```

Ok, I will add a dummy test.

**Comment by uvchik** [comment]
> Make dummy test comparison non-redundant

Sorry @jnnr

**Comment by jnnr** [comment]
No problem!

**Comment by jakob-wo** [comment]
Great, thanks to both of you!

**Pull request merged**
