### PR TITLE
Improvements of strat. therm. storage examples 

### PR DESCRIPTION
**Pull request by jakob-wo**
This PR introduces several improvements regarding the examples on the stratified thermal storage examples.

- [x] Remove outdated warnings/comments in code <-- already done in PR #154
- [x] Remove outdated warnings/comments in docu <-- already done in PR #154
- [ ] Add description to example (comment on top)
- [x] Shorten example names & make example names more speaking
- [ ] Clearify the usage of `efficiency`, `inflow_conversion_factor `and `outflow_conversion_factor`
- [ ] Clearify that example `stratified_thermal_storage_facade.py` does not solve the optimization model but compares lp-files OR change example and make it solve the problem

This PR is related to Issue #129 and #130.

### CODE REVIEW

**Comment by jakob-wo** [comment]
@jnnr, please have a look at the new example names and give me a feedback. It is a first suggestion and its structure (v1_, v2_ etc.) is taken from the examples of oemof.solph: [storage_investment ](https://github.com/oemof/oemof-examples/tree/master/oemof_examples/oemof.solph/v0.4.x/storage_investment)

**Comment by jakob-wo** [comment]
PR #154 already updated/removed outdated Warnings. 
So all commits in this PR regarding these changes have to be checked/removed.

**Comment by jakob-wo** [comment]
I don't have the time to finish this PR before my research project ends :( 
@jnnr, if you find the suggested changes usefull, please carry on with this PR.

**Comment by jnnr** [comment]
Closed in favor of #168

**Pull request closed without merging**
