### PR TITLE
Unite tests in one test file

### PR DESCRIPTION
**Pull request by c-moeller**
#78

### CODE REVIEW

**Comment by c-moeller** [comment]
@FranziPl @jakob-wo Could you quickly scan the file test_functions.py if I didn't miss any of your tests?

**Comment by jakob-wo** [comment]
All tests from tests_compression_heatpumps_and_chillers.py were transfered/copied.

**Comment by FranziPl** [comment]
All csp tests are there too.

**Comment by c-moeller** [comment]
@FranziPl @jakob-wo Could one of you approve this PR? Then I will be able to merge.

**Review by FranziPl — APPROVED** [review]

**Pull request merged**
