### PR TITLE
Add function tests for solar thermal collector

### LINKED ISSUE #34: There are no tests
We do not have any tests yet. It would be very helpful for developers to have some automatic tests. I suggest that we do the following: First, think about how reasonable tests for the package would look like. Then, the contributors to the different modules write some tests for the functions.

TODO

* [x] Write tests for solar_thermal_collector

### PR DESCRIPTION
**Pull request by MaGering**
Adds first sketch of tests for the module solar thermal collector. 
Related issue: https://github.com/oemof/oemof-thermal/issues/34

### CODE REVIEW

**Comment by c-moeller** [comment]
@MaGering Please add the external calculated values to the tests.
@FranziPl Please review the code.
Thanks a lot!

**Comment by MaGering** [comment]
> @MaGering Please add the external calculated values to the tests.

I've calculated the values in an external script. They are equal to the values calculated within solar_thermal_collector.py, which I used in test_functions.py as placeholders so far. This means that test_functions.py does not change.

**Review by FranziPl — APPROVED** [review]
Looks fine to me.

**Comment by jnnr** [comment]
This one seems ready to merge. @MaGering: Can you please resolve the merge conflict?

**Pull request merged**
