### PR TITLE
Remove personal entry from gitignore

### PR DESCRIPTION
**Pull request by FranziPl**
I removed my personal entries from the gitignore file to solve #85. I added my directory to results, because I still need it.
@jnnr I am not sure, how we can bring the results together in one entry, because they are in different directories?

### CODE REVIEW

**Comment by jakob-wo** [comment]
I am not sure but maybe something like _examples/**/results_ in the gitignore-file will work as a generic solution.
Therefore it would be necessary to rename _csp_results_ --> _results_.

**Comment by FranziPl** [comment]
So I changed the name of the folder, so one entry for all results should work.
@c-moeller and @jakob-wo, can you have a look, if it works for you too?

**Comment by jnnr** [comment]
I agree with the changes made here. Two things have to be fixed however before merging. For the examples in concentrating_solar_power and solar_thermal_collector, the results directory has to be created before the results are stored. Use `os.mkdir()`. Otherwise, the user gets a "path not found" error.

**Review by jnnr — CHANGES_REQUESTED** [review]
I agree with the changes made here. Two things have to be fixed however before merging. For the examples in concentrating_solar_power and solar_thermal_collector, the results directory has to be created before the results are stored. Use `os.mkdir()`. Otherwise, the user gets a "path not found" error.

```
results_path = os.path.join(path,'examples', 'solar_thermal_collector', 'results')
if not os.path.exists(results_path):
    os.mkdir(results_path)
```

Adapted the code accordingly (see the commits below).

**Review by jnnr — APPROVED** [review]

**Comment by FranziPl** [comment]
Thanks @jnnr for creating the paths.

**Pull request merged**
